KSRescue support for ERC721 & ERC1155
KyberNetwork/ks-growth-utils-sc pull request #5
Opened 2024-06-05 09:56 UTC by qcuong98

2024-06-05 10:08 UTC, Zohar97 requested changes

2024-06-05 10:08 UTC, Zohar97 commented on contracts/KSRescueV2.sol
> +      if (amounts[i] == 0) amounts[i] = _getAvailableAmountERC1155(token, ids[i]);
should update this

2024-06-05 10:19 UTC, Zohar97 commented on contracts/KSRescueV2.sol
> +    require(ids.length == amounts.length);
Should add message revert

2024-06-05 10:31 UTC, Zohar97 approved these changes

2024-06-11 03:42 UTC, vutt94 approved these changes

2024-06-17 07:58 UTC, vutt94 approved these changes

2024-06-17 08:00 UTC, merged